version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: "root"
    networks:
      - health

  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - db:/data/mongosh
    networks:
      - health

  healthservice:
    container_name: health
    build: .
    ports:
      - "5551:5551"
    networks:
      - health

networks:
  health:
    name: health
    driver: bridge
    external: true

volumes:
  db:
